### PR TITLE
Restructure Project Code. Add README. Add LICENCE.

### PR DESCRIPTION
**Pull request by dvaldivia**
This PR restructures the project code to be easier to clone into a `$GOROOT` and run.

Also added a basic README.md and LICENCE

### CODE REVIEW

**Comment by dvaldivia** [comment]
While running the tests I only get the following failure

```
Test ignored.
=== RUN   TestBasic
--- PASS: TestBasic (0.00s)
=== RUN   TestTypes
--- PASS: TestTypes (0.00s)
=== RUN   TestDisconnect
--- PASS: TestDisconnect (0.01s)
=== RUN   TestCounts
--- PASS: TestCounts (0.00s)
=== RUN   TestConcurrentMany
--- PASS: TestConcurrentMany (0.00s)
=== RUN   TestUnreliable
--- PASS: TestUnreliable (0.03s)
=== RUN   TestConcurrentOne
--- PASS: TestConcurrentOne (0.00s)
=== RUN   TestRegression1
--- PASS: TestRegression1 (0.10s)
=== RUN   TestKilled
--- PASS: TestKilled (1.11s)
=== RUN   TestBenchmark
2.049420194s for 100000
--- PASS: TestBenchmark (2.05s)
PASS
ok  	raft/labrpc	(cached)
=== RUN   TestVote
=== RUN   TestVote/1st_election,_1st_request,_granted
Server 0 received RequestVote from 1: &{Term:1 CandidateID:1 LastLogIndex:0 LastLogTerm:0}
Server 0 received RequestVote from 1 and got lock.
Server 0 is transitioning/voting.
Server 0 is transitioning from 0 to 0.
Interrupting.
Server 0 is a follower. Term is 1. Role was 0.
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x106f9f6]

goroutine 6 [running]:
testing.tRunner.func1(0xc4200c01e0)
	/usr/local/go/src/testing/testing.go:742 +0x29d
panic(0x11b1540, 0x12e25e0)
	/usr/local/go/src/runtime/panic.go:502 +0x229
time.(*Timer).Reset(0x0, 0x10bfb840, 0x0)
	/usr/local/go/src/time/sleep.go:124 +0x26
raft/raft.(*Raft).restartElectionTimer(0xc4200c8010)
	/Users/dvaldivia/go/src/raft/raft/raft.go:734 +0x57
raft/raft.(*Raft).Vote(0xc4200c8010, 0xc4200c8100, 0xc420081ee0)
	/Users/dvaldivia/go/src/raft/raft/raft.go:717 +0x5f5
raft/raft.TestVote.func1(0xc4200c01e0)
	/Users/dvaldivia/go/src/raft/raft/raft_test.go:153 +0x83
testing.tRunner(0xc4200c01e0, 0xc42005f3a0)
	/usr/local/go/src/testing/testing.go:777 +0xd0
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:824 +0x2e0
FAIL	raft/raft	0.013s
```

**Comment by dvaldivia** [comment]
Test `TestVote()` fails because the `electionTimer` on `Raft` is never initializer, therefore nil

**Comment by dvaldivia** [comment]
by doing the following https://github.com/dvaldivia/raft/commit/6d875b910d82b7089078bde9bed5b64558039e77

I get the following results, but sucessfully run tests

```
GOROOT=/usr/local/go #gosetup
GOPATH=/Users/dvaldivia/go #gosetup
/usr/local/go/bin/go test -json ./... #gosetup
=== RUN   TestBasic
--- PASS: TestBasic (0.00s)
=== RUN   TestTypes
--- PASS: TestTypes (0.00s)
=== RUN   TestDisconnect
--- PASS: TestDisconnect (0.01s)
=== RUN   TestCounts
--- PASS: TestCounts (0.00s)
=== RUN   TestConcurrentMany
--- PASS: TestConcurrentMany (0.00s)
=== RUN   TestUnreliable
--- PASS: TestUnreliable (0.03s)
=== RUN   TestConcurrentOne
--- PASS: TestConcurrentOne (0.00s)
=== RUN   TestRegression1
--- PASS: TestRegression1 (0.10s)
=== RUN   TestKilled
--- PASS: TestKilled (1.11s)
=== RUN   TestBenchmark
2.049420194s for 100000
--- PASS: TestBenchmark (2.05s)
PASS
ok  	raft/labrpc	(cached)
=== RUN   TestVote
=== RUN   TestVote/1st_election,_1st_request,_granted
Server 0 started the timer.
Server 0 received RequestVote from 1: &{Term:1 CandidateID:1 LastLogIndex:0 LastLogTerm:0}
Server 0 received RequestVote from 1 and got lock.
Server 0 is transitioning/voting.
Server 0 is transitioning from 0 to 0.
Interrupting.
Server 0 is a follower. Term is 1. Role was 0.
Server 0 restarted the timer.
Vote request to server 0 responded: {Term:1 VoteGranted:true}
=== RUN   TestVote/1st_election,_voted_already,_denied
Server 0 started the timer.
Server 0 received RequestVote from 1: &{Term:1 CandidateID:1 LastLogIndex:0 LastLogTerm:0}
Server 0 received RequestVote from 1 and got lock.
Server 0 already voted for 2 in term 1.
=== RUN   TestVote/Stale_candidate_request,_denied
Server 0 started the timer.
Server 0 received RequestVote from 1: &{Term:1 CandidateID:1 LastLogIndex:0 LastLogTerm:0}
Server 0 received RequestVote from 1 and got lock.
Server 0 denied vote to 1 because of stale term 1.
=== RUN   TestVote/Stale_candidate_voter,_drop_out_of_race,_granted
Server 2 started the timer.
Server 2 received RequestVote from 1: &{Term:2 CandidateID:1 LastLogIndex:0 LastLogTerm:0}
Server 2 received RequestVote from 1 and got lock.
Server 2 is transitioning/voting.
Server 2 is transitioning from 1 to 0.
Interrupting.
Server 2 is a follower. Term is 2. Role was 1.
Server 2 restarted the timer.
Vote request to server 2 responded: {Term:2 VoteGranted:true}
=== RUN   TestVote/Stale_leader_voter,_step_down,_granted
Server 2 started the timer.
Server 2 received RequestVote from 1: &{Term:2 CandidateID:1 LastLogIndex:0 LastLogTerm:0}
Server 2 received RequestVote from 1 and got lock.
Server 2 is transitioning/voting.
Server 2 is transitioning from 2 to 0.
Interrupting.
Server 2 is a follower. Term is 2. Role was 2.
Server 2 restarted the timer.
Vote request to server 2 responded: {Term:2 VoteGranted:true}
--- PASS: TestVote (0.00s)
    --- PASS: TestVote/1st_election,_1st_request,_granted (0.00s)
    --- PASS: TestVote/1st_election,_voted_already,_denied (0.00s)
    --- PASS: TestVote/Stale_candidate_request,_denied (0.00s)
    --- PASS: TestVote/Stale_candidate_voter,_drop_out_of_race,_granted (0.00s)
    --- PASS: TestVote/Stale_leader_voter,_step_down,_granted (0.00s)
=== RUN   TestAppendEntries
=== RUN   TestAppendEntries/1st_heartbeat,_success
Server 2 started the timer.
Server 2 received AppendEntries from 0: &{Term:1 LeaderID:0 PrevLogIndex:0 PrevLogTerm:0 LeaderCommit:0 Entries:[{Term:0 Command:<nil>}]}
Server 2 received AppendEntries from 0 and got lock.
Server 2 restarted the timer.
AppendEntries request to server 2 responded: {Term:1 Success:true Peer:2}
=== RUN   TestAppendEntries/Heartbeat,_leader,_transition,_success
Server 2 started the timer.
Server 2 received AppendEntries from 0: &{Term:2 LeaderID:0 PrevLogIndex:0 PrevLogTerm:0 LeaderCommit:0 Entries:[{Term:0 Command:<nil>}]}
Server 2 received AppendEntries from 0 and got lock.
Server 2 is transitioning from 2 to 0.
Interrupting.
Server 2 is a follower. Term is 2. Role was 2.
Server 2 restarted the timer.
AppendEntries request to server 2 responded: {Term:2 Success:true Peer:2}
=== RUN   TestAppendEntries/Heartbeat,_candidate,_transition,_success
Server 2 started the timer.
Server 2 received AppendEntries from 0: &{Term:2 LeaderID:0 PrevLogIndex:0 PrevLogTerm:0 LeaderCommit:0 Entries:[{Term:0 Command:<nil>}]}
Server 2 received AppendEntries from 0 and got lock.
Server 2 is transitioning from 1 to 0.
Interrupting.
Server 2 is a follower. Term is 2. Role was 1.
Server 2 restarted the timer.
AppendEntries request to server 2 responded: {Term:2 Success:true Peer:2}
=== RUN   TestAppendEntries/1st_entry,_success
Server 2 started the timer.
Server 2 received AppendEntries from 0: &{Term:1 LeaderID:0 PrevLogIndex:0 PrevLogTerm:0 LeaderCommit:0 Entries:[{Term:1 Command:cmd}]}
Server 2 received AppendEntries from 0 and got lock.
Server 2 restarted the timer.
AppendEntries request to server 2 responded: {Term:1 Success:true Peer:2}
=== RUN   TestAppendEntries/2nd_entry,_success
Server 2 started the timer.
Server 2 received AppendEntries from 0: &{Term:1 LeaderID:0 PrevLogIndex:1 PrevLogTerm:1 LeaderCommit:0 Entries:[{Term:1 Command:cmd}]}
Server 2 received AppendEntries from 0 and got lock.
Server 2 restarted the timer.
AppendEntries request to server 2 responded: {Term:1 Success:true Peer:2}
=== RUN   TestAppendEntries/Multiple_entries,_success
Server 2 started the timer.
Server 2 received AppendEntries from 0: &{Term:1 LeaderID:0 PrevLogIndex:0 PrevLogTerm:0 LeaderCommit:0 Entries:[{Term:1 Command:cmd} {Term:1 Command:cmd}]}
Server 2 received AppendEntries from 0 and got lock.
Server 2 restarted the timer.
AppendEntries request to server 2 responded: {Term:1 Success:true Peer:2}
=== RUN   TestAppendEntries/Stale_leader,_failure
Server 2 started the timer.
Server 2 received AppendEntries from 0: &{Term:1 LeaderID:0 PrevLogIndex:0 PrevLogTerm:0 LeaderCommit:0 Entries:[]}
Server 2 received AppendEntries from 0 and got lock.
AppendEntries request to server 2 is stale.
=== RUN   TestAppendEntries/Request_doesn't_match_log,_failure
Server 2 started the timer.
Server 2 received AppendEntries from 0: &{Term:1 LeaderID:0 PrevLogIndex:1 PrevLogTerm:1 LeaderCommit:0 Entries:[{Term:1 Command:cmd}]}
Server 2 received AppendEntries from 0 and got lock.
Server 2 restarted the timer.
AppendEntries request to server 2 failed to pass the log check.
=== RUN   TestAppendEntries/Follower_has_extra_entries,_remove,_success
Server 2 started the timer.
Server 2 received AppendEntries from 0: &{Term:2 LeaderID:0 PrevLogIndex:0 PrevLogTerm:0 LeaderCommit:0 Entries:[{Term:0 Command:<nil>}]}
Server 2 received AppendEntries from 0 and got lock.
Server 2 is transitioning from 0 to 0.
Interrupting.
Server 2 is a follower. Term is 2. Role was 0.
Server 2 restarted the timer.
AppendEntries request to server 2 responded: {Term:2 Success:true Peer:2}
--- FAIL: TestAppendEntries (0.00s)
    --- FAIL: TestAppendEntries/1st_heartbeat,_success (0.00s)
    	raft_test.go:417: reply: got {Term:1 Success:true Peer:2}, want {Term:1 Success:true Peer:0}
    --- FAIL: TestAppendEntries/Heartbeat,_leader,_transition,_success (0.00s)
    	raft_test.go:417: reply: got {Term:2 Success:true Peer:2}, want {Term:2 Success:true Peer:0}
    --- FAIL: TestAppendEntries/Heartbeat,_candidate,_transition,_success (0.00s)
    	raft_test.go:417: reply: got {Term:2 Success:true Peer:2}, want {Term:2 Success:true Peer:0}
    --- FAIL: TestAppendEntries/1st_entry,_success (0.00s)
    	raft_test.go:417: reply: got {Term:1 Success:true Peer:2}, want {Term:1 Success:true Peer:0}
    --- FAIL: TestAppendEntries/2nd_entry,_success (0.00s)
    	raft_test.go:417: reply: got {Term:1 Success:true Peer:2}, want {Term:1 Success:true Peer:0}
    --- FAIL: TestAppendEntries/Multiple_entries,_success (0.00s)
    	raft_test.go:417: reply: got {Term:1 Success:true Peer:2}, want {Term:1 Success:true Peer:0}
    --- FAIL: TestAppendEntries/Stale_leader,_failure (0.00s)
    	raft_test.go:417: reply: got {Term:2 Success:false Peer:2}, want {Term:2 Success:false Peer:0}
    --- FAIL: TestAppendEntries/Request_doesn't_match_log,_failure (0.00s)
    	raft_test.go:417: reply: got {Term:1 Success:false Peer:2}, want {Term:1 Success:false Peer:0}
    --- FAIL: TestAppendEntries/Follower_has_extra_entries,_remove,_success (0.00s)
    	raft_test.go:417: reply: got {Term:2 Success:true Peer:2}, want {Term:2 Success:true Peer:0}
=== RUN   TestReplicateLog
Server 0 started the timer.
Server 0 is applying entries.
Server 1 started the timer.
Server 2 started the timer.
Server 1 is applying entries.
Server 2 is applying entries.
The timer of server 2 expired.
Server 2 is transitioning from 0 to 1.
Interrupting.
Server 2 is a candidate. Term is 2. Role was 0.
Server 2 restarted the timer.
panic: makechan: size out of range

goroutine 31 [running]:
raft/raft.(*Raft).requestVotes(0xc4200d4010, 0x2, 0x1, 0x0, 0xc420089980)
	/Users/dvaldivia/go/src/raft/raft/raft.go:587 +0x82
created by raft/raft.(*Raft).enterCandidate
	/Users/dvaldivia/go/src/raft/raft/raft.go:181 +0x215
FAIL	raft/raft	0.163s

```

**Comment by carlos-lopez-garces** [comment]
Thank you @dvaldivia!

**Pull request merged**
